language: node_js
node_js:
  - 4.0.0
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
sudo: true
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
- npm install webpack@1.14.0
- npm install protractor@5.0.0
- ./node_modules/protractor/bin/webdriver-manager update
script:
- npm run build:local
- npm run test
- node server.test.js &
- npm run test-e2e
env:
  global:
  - BUILD=1
  - REMOTE_TESTS=1
  - CXX=g++-4.8
