language: node_js
node_js:
  - 6.9.4
sudo: true
cache:
  directories:
  - node_modules
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
- npm install webpack
- npm install protractor@5.0.0
- ./node_modules/protractor/bin/webdriver-manager update
script:
- npm run build:local
- npm run test
- node server.test.js &
- npm run test-e2e
