sudo: required
language: node_js
node_js:
  - 6.9.4
addons:
  firefox: "48.0"
install:
- npm install
- npm install selenium-webdriver
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - ./node_modules/protractor/bin/webdriver-manager update
script:
- npm run build
- npm run test
- node server.test.js &
- npm run e2e
cache:
  directories:
    - node_modules
